const POST_REQUEST = 'POST_REQUEST';
const POST_SUCCESS = 'POST_SUCCESS';
const POST_FAILURE = 'POST_FAILURE';
const USER_REQUEST = 'USER_REQUEST';
const USER_SUCCESS = 'USER_SUCCESS';
const USER_FAILURE = 'USER_FAILURE';
const COMMENT_REQUEST = 'COMMENT_REQUEST';
const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
const COMMENT_FAILURE = 'COMMENT_FAILURE';
const CLEAN_STATE = 'CLEAN_STATE';

export {
    POST_REQUEST,
    POST_SUCCESS,
    POST_FAILURE,
    USER_REQUEST,
    USER_SUCCESS,
    USER_FAILURE,
    COMMENT_REQUEST,
    COMMENT_SUCCESS,
    COMMENT_FAILURE,
    CLEAN_STATE
}